<?php

//No direct access to this file
defined("_JEXEC") or die("Restricted Access");

//import Joomla libary
jimport("joomla.application.component.view");

/**
 * Class PunishmentViewUserViolation
 *
 * Date: 11.11.13
 * Time: 10:25
 * @author Thomas Joußen <tjoussen@databay.de>
 */ 
class PunishmentViewUserViolation extends JView{

	/**
	 * @var JObject
	 */
	protected $canDo;

	public function __construct($config = array())
	{
		parent::__construct($config); // TODO: Change the autogenerated stub

		JLoader::import('punishment', JPATH_ROOT . DS . 'components' . DS . 'com_punishment' . DS . 'helpers' );
		$this->canDo = PunishmentHelper::getActions();
	}

	function display($tpl = null)
	{
		$this->form = $this->get("Form");
		$this->item = $this->get("Item");

		parent::display($tpl);
	}
}
 